#!/bin/sh /etc/rc.common

## Netkickd init script.
##
## This is a part of the Project Shuppie.
## License: GNU General Public License v3.
## Copyright © Raegdan, 2015.
## All rights reserved.
## Email: raegdan-at-gmail-dot-com.

START=90
STOP=10

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/netkickd
	procd_close_instance
}

stop_service() {
	rm -fv /tmp/netkick.*.lock
}
