#!/bin/sh

## Netkickd: daemon continuously checking connectivity against
## specified IP and triggers netkick in case of fault.
##
## This is a part of the Project Shuppie.
## License: GNU General Public License v3.
## Copyright © Raegdan, 2015.
## All rights reserved.
## Email: raegdan-at-gmail-dot-com.

## IP to test against. Should be the same as in netkick.
## OpenVPN gateway is good choice if its uptime is fine.
TESTING_IP="8.8.8.8"

## Interval between checks in syntax of /bin/sleep.
INTERVAL="10s"

## Ping session packets count. If one packet fails - all session fails, so be careful increasing this.
PING_COUNT="1"

## C O D E ##

logger -t netkickd "Netkickd started: test against $TESTING_IP every $INTERVAL with $PING_COUNT ping(s) in a burst."

while [ 1 ] ; do
    /bin/ping -n -c $PING_COUNT $TESTING_IP 2>&1 > /dev/null
    if [ $? -ne 0 ] ; then
        logger -t netkickd "No network detected, netkicking now"
        /usr/sbin/netkick &
    fi

    /bin/sleep $INTERVAL
done
