#!/bin/sh

## Restarts Tor and Tor's fellow Polipo on status change of interfaces having "wan" or "vpn" (case-insens.) in their names.
##
## This is a part of the Project Shuppie.
## License: GNU General Public License v3.
## Copyright © Raegdan, 2015.
## All rights reserved.
## Email: raegdan-at-gmail-dot-com.

[ "$ACTION" = ifup -o "$ACTION" = ifupdate -o "$ACTION" = ifdown ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

[ $( echo "$INTERFACE" | grep -iE "vpn|wan" ) ] || exit 0
/etc/init.d/tor enabled && /etc/init.d/polipo enabled || exit 0

logger -t tor "Restarting Tor due to $ACTION of WAN iface $INTERFACE ($DEVICE)"
/etc/init.d/polipo stop
/etc/init.d/tor stop
/bin/sleep 1s
/etc/init.d/tor start
/etc/init.d/polipo start
